version: '3.3'

services:
  db:
    env_file:
      - .env
    image: mongo
    # ports:
    #   - '27017:27017'
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME} #I think this is not needed
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD} #I think this is not needed
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE} #I think this is not needed
      MONGO_USERNAME: ${MONGO_APP_USER} #This too... just change standardize variables name!
      MONGO_PASSWORD: ${MONGO_APP_PASS} #This too... just change standardize variables name!
    volumes:
      # - /data:/data/db
      - ./mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

  cache:
    env_file:
      - .env
    image: redis:alpine
    restart: unless-stopped
    # ports:
    #   - '6379:6379'
    command: ['--requirepass "${REDIS_PASSWORD}"']

  api:
    build:
      context: ../
      dockerfile: ./docker/api.Dockerfile
    restart: unless-stopped
    user: 1000:1000
    depends_on:
      - db
      - cache
    links:
      - db
      - cache
    # ports:
    #   - '3000:3000'

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"  


  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"  