import { Constants } from "../utils";

export const
    BCRYPT_WORK_FACTOR = 12,
    BCRYPT_MAX_BYTES = 72,
    EMAIL_VERIFICATION_TIMEOUT = Constants.TWELVE_HOURS_MILLISEC,
    EMAIL_VERIFICATION_TOKEN_BYTES = 40,
    EMAIL_VERIFICATION_SIGNATURE_BYTES = 64,
    PASSWORD_RESET_BYTES = 40,
    PASSWORD_RESET_TIMEOUT = Constants.ONE_HOUR_MILLISEC;
